= A collection of Db2 for z/OS user-defined functions (UDFs): Several scalar and table functions that I wish were part of Db2 for z/OS but are not.
//
:toc: left
:toclevels: 3
:icons: font
:source-highlighter: rouge


This project is a collection of several useful Db2 routines (user-defined functions and stored procedures). They add functionality in
multiple categories; for example, data type conversion, formatting, and easy invocation of Db2 utilities.

[IMPORTANT]
**Security Notice**: Before deploying these functions in a production environment, please review the link:SECURITY.md[Security Policy] and follow the security best practices outlined there.


Many functions are implemented as SQL functions which makes them very easy to deploy
-- just run the DDL.
Others are implemented as external functions, written in C, COBOL or Java.
Of particular interest is <<READ_GENERIC_FILE>> which is a rare example of a generic table function
(a table function that allows for dynamic specification of the result table's structure).

Even if you do not find the routines useful (which would be a pity), you should find some
examples for techniques that you _do_ find useful; e.g., recursive table expressions. 

== Overview

The following table shows an overview of all functions:

[options="header,autowidth",width="100%"]
|===
|Function               |Type |Category      |Description |Implemented in
|<<APFLIST>>            |T    |System        |Returns a table with all APF authorized data sets on the system. |COBOL
|<<BASE64DECODE>>       |S    |Data types    |Decodes BASE64 format to binary data.                            |Java
|<<BASE64ENCODE>>       |S    |Data types    |Encodes binary data to BASE64 format.                            |Java
|<<CROSSLOAD>>          |S    |Utilities     |Copies data from one table to another.                           |SQL
|<<DB2UTILITY>>         |S    |Utilities     |Runs one or more Db2 utility statements.                         |SQL
|<<EASTER>>             |S    |Date and time |Calculates the date of Easter for a given year.                  |SQL
|<<FORMATTIMESTAMP>>    |S    |Date and time |Locale-sensitive formatting of a timestamp value.                |Java
|<<GENERATE_SERIES>>    |T    |Data types    |Generate a series of values between a start and an end value, 
                                              with an optional step.                                           |SQL
|<<HEXTOINT>>           |S    |Data types    |Converts a hex string to integer.                                |SQL
|<<RACFPROFILE>>        |S    |System        |Returns the RACF profile that covers the input data set name.    |COBOL
|<<READ_GENERIC_FILE>>  |T    |System        |Reads records from a flat file and returns them as a table.      |C
|<<REGEX_MATCHES>>      |S    |Strings       |Matches a regular expression against a string.                   |Java or SQL
|<<REGEX_REPLACE>>      |S    |Strings       |Replaces regular expression matches within a string.             |Java
|<<RUNSTATS>>           |S    |Utilities     |Runs statistics against a table or a set of tables.              |SQL
|<<SPLIT>>              |T    |Text          |Tokenizes a comma-separated string (inverse of LISTAGG).         |SQL
|<<SPRINTF>>            |T    |Text          |Formats one or more values according to a Java-style
                                              format string.                                                   |Java
|xref::submit[SUBMIT]   |S    |Utilities     |Submits a JCL job stream and returns the job output as a CLOB.   |SQL
|xref::submit[SUBMIT_T] |T    |Utilities     |Submits a JCL job stream and returns the job output as a table.  |SQL
|<<TO_ROMAN>>           |S    |Data types    |Converts a small integer to a Roman numeral. |SQL
a|xref::try_integer[TRY_INTEGER +
TRY_SMALLINT +
TRY_BIGINT]  
                        |S    |Data types    |Returns text converted to an integer or NULL on failure.         |SQL
|<<VALIDATE_CONVERSION>> |T   |Data types    |Tests whether a given character string can be converted
                                              to a specified target type.                                      |SQL
|===

== Installation

The installation of each function differs on the function implementation.

The functions can be installed into an installation-defined schema or into the Db2 standard SYSFUN schema.
Installing into SYSFUN has the advantage that you do not need to qualify the function name or set the 
CURRENT FUNCTION PATH special register;
it has the disadvantage of risking incompatibilities if a future version of Db2
defines built-in functions with the same name.

*SQL functions* can be installed by simply running the supplied DDL.

*External functions* in a compiled language (C or COBOL) need to be compiled, link-edited and
placed in a library that is part of the WLM environment's STEPLIB concatenation.

External functions written in *Java* can be installed by creating a Jar and placing that Jar
either into the CLASSPATH of the Java Virtual Machine running in your Java WLM environment,
or by placing the Jar into the Db2 catalog using the SQLJ_DB2_INSTALL_JAR stored procedure. 

== Date and time

=== EASTER

Returns the date of Easter Sunday in the given year, which
must be a year after the Gregorian calendar reform (>= 1583).

[subs="quotes"]
----
easter(_year_)
----

The argument can be an integer greater than or equal to the year
of the Gregorian calendar reform (1583). Otherwise, an error 
condition (SQLSTATE 71583) is raised.

If the argument is null, the result is the null value.

Examples:

[,sql]
----
select current date as today, easter(year(current date)) as easter
  from sysibm.sysdummyu;
----

[,sql]
----
select easter(1582) from sysibm.sysdummyu;
----

Using the <<GENERATE_SERIES>> function, we can find
out the Easter dates for the next 50 years:

[,sql]
----
select easter(value) as "Easter Sunday"
  from table(generate_series(2000, 2050));
----


== Data types

=== VALIDATE_CONVERSION
:!seq1:

Tests whether a given character string can be converted
to the specified built-in data type.

[subs="quotes"]
----
validate_conversion(_source_string_, _target_type_)
----

The VALIDATE_CONVERSION function tests whether a given character string can be converted
to the specified built-in data type.
If the string can be successfully converted, returns 1;
otherwise, returns 0.

If the string is null, returns 1 since any built-in data type supports null values.

If target_type does not specify a valid built-in type name, 
an error condition is signaled. User-defined types are not supported.

source_string:: The source string to be tested.
target_type:: The target data type.

The result of the function is an integer. The result cannot be null.

.Example {counter:ex}
[,sql]
----
select validate_conversion('2024-01-09', 'date') from sysibm.sysdummyu
----

.Example {counter:ex}
[,sql]
----
with
d(d) as (
  select 1 from sysibm.sysdummyu
),
tests(value, type, expected_result) as (
            select '42',         'integer',       1 from d 
  union all select '42',         'smallint',      1 from d 
  union all select '42',         'bigint',        1 from d 
  union all select '42',         'smallint',      1 from d 
  union all select '  42  ',     'smallint',      1 from d  -- leading and trailing blanks ok
  union all select 'junk',       'integer',       0 from d  -- complete junk not ok
  union all select '2147483647', 'integer',       1 from d  -- within range 
  union all select '2147483648', 'integer',       0 from d  -- not within range
  union all select '-2147483648', 'integer',      0 from d  -- within range
  union all select '2024-01-09', 'date',          1 from d 
  union all select '1.9.2024',   'date',          1 from d 
  union all select '2024-02-30', 'date',          0 from d  -- No February 30 
  union all select '29.2.2024',  'date',          1 from d  -- Leap year, European date format 
  union all select '29.2.2023',  'date',          0 from d  -- Not a leap year
  union all select '47.11',      'decimal(4, 2)', 1 from d  -- Precision and scale ok
  union all select '-47.11',     'decimal(4, 2)', 1 from d  -- Negative ok
  union all select '47.11',      'decimal(3, 2)', 0 from d  -- Insufficient precision 
  union all select '47.11',      'decimal(3, 1)', 1 from d  -- With truncation of scale, precision now ok 
  union all select '2024.98765', 'decfloat',      1 from d 
  union all select '2024-01-25 16:15:14.12345+01:00',
                   'timestamp(0) with timezone',  1 from d
  union all select cast(null as char), 'integer', 1 from d  -- Nulls ok                                  
),
results as (
  select row_number() over() as row
       , tests.*
       , validate_conversion(value, type) actual_result
    from tests
)
select *
  from results
 where expected_result <> actual_result
    OR 1 = 1 -- remove to see wrong results only
----

[[:try_integer]]
=== TRY_INTEGER, TRY_SMALLINT, TRY_BIGINT

The TRY___xxx__ functions try to convert the string value passed to an integer type; if the conversion fails, they return
NULL instead of signaling an error.

[sql,subs="quotes"]
----
TRY_SMALLINT(_string_expression_)
TRY_INTEGER(_string_expression_)
TRY_BIGINT(_string_expression_)
----

string-expression::
An expression that returns a value of a character or graphic string (except a CLOB or DBCLOB)
with a length attribute that is not greater than 255 bytes.
Leading and trailing blanks are eliminated.

The TRY___xxx__ functions try to convert the string value passed to an integer type.

The conversion is performed in the same way as the respective built-in function and follows the same rules.
Leading or trailing blanks are therefore permitted, and the fractional part of the argument is truncated.

The difference to the built-in functions is the behavior when the input string is not a valid string representation of an integer type, 
or if the integer value is out of range for the target type.
In this case, NULL is returned and an SQL warning (SQLSTATE 02018) is raised.

If the argument is null, the result is the null value.

Example:

[sql,subs="quotes"]
----
select try_integer('42')        answer1,
        try_integer('  42  ')   answer2,
        try_integer('fortytwo') answer3
  from sysibm.sysdummy1;
----

[options="header,autowidth",width="100%"]
|===
| ANSWER1 |ANSWER2  |ANSWER3
|      42 |     42  |  NULL
|===



=== HEXTOINT

The HEXTOINT function converts the hexadecimal string representation of a number to the numeric value. It can be considered the inverse of the HEX function with a BIGINT argument.

[sql,subs="quotes"]
----
HEXTOINT(_hexstring_)
----

hexstring:: A non-empty character string containing the valid hexadecimal representation of a number in BIGINT range.

The input string must not be empty, and must contain upper-case or lower-case hex digits only (0..9, A..F, a..f); otherwise, SQLSTATE 72606 is raised. Leading or trailing whitespace,
therefore, is not permitted.

If called with a null argument, the function returns the null value.

The hex string must represent a number within the range of a BIGINT, otherwise, an overflow condition is raised (SQLSTATE 22003).

.Example:
[,sql]
----
select hextoint('DEADBEEF') as intval
  from sysibm.sysdummyu
----

.Result:
[options="header,autowidth",width="100%"]
|===
| INTVAL
| 3735928559
|===



=== GENERATE_SERIES

Generates a series of integer values in the given interval.

[source,sql,subs="quotes"]
----
GENERATE_SERIES(_start_, _stop_)
----

[source,sql,subs="quotes"]
----
GENERATE_SERIES(_start_, _stop_, _step_)
----


The GENERATE_SERIES table function generates a series of integer values in the given interval 
from _start_ to _stop_, with an optional _step_. Both _start_ and _stop_ are inclusive; _step_, if
specified, must not be 0. No rows are returned if _start_ > _stop_ and _step_
is positive, or _start_ < _stop_ and _step_ is negative, or if any parameter
is NULL.

start::
  The start of the interval.
stop::
  The end of the interval.
step::
  The increment between consecutive values.  

.Example:
[source,sql]
----
select value from table(generate_series(1, 5));
----

.Result:
 VALUE
 -----
 1
 2
 3
 4
 5

.Example:
[source,sql]
----
select value from table(generate_series(1, 9, 3));
----

.Result:
 VALUE
 -----
 1
 4
 7

.Example:
[source,sql]
----
select value as countdown from table(generate_series(3, 0, -1));
----

.Result:
....
 COUNTDOWN
 ---------
 3
 2
 1
 0
....

.Example:
[source,sql]
----
-- 42 random integers in the range [0, 100)
select integer(rand() * 100) from table(generate_series(1, 42));
----

For another example, see the <<EASTER>> function.

== Text



=== SPLIT

The SPLIT function tokenizes a comma-separated string and returns one row per token. It can be considered the inverse of LISTAGG(values, ',').

[sql,subs="quotes"]
----
split(_input_ varchar(32704))
returns table (seqno integer, token varchar(32704))
----

input:: A character string that contains comma-separated tokens. If a comma is part of a token, i.e. should _not_ be considered a
token separator, it must be escaped with the `\' character. The input string must not contain Unicode character x'241E' (Record separator)
as this character is used internally for escaping.

The function returns a table containing the individual tokens and a sequence number starting with 1.
It is particularly useful with IN predicates if the number of values to test against is known only at runtime,
see Example.


Example 1:

[sql,subs="quotes"]
----
select *
  from table(split('EMP,DEPT,PARTS,SUPPLIERS'));
----

.Result:
[options="header,autowidth"]
|===
|SEQNO|TOKEN    
|1    |EMP      
|2    |DEPT     
|3    |PARTS    
|4    |SUPPLIERS
|===
  
Example 2:

To supply the values for an IN predicate where the number of values is known only at runtime,
pass a host variable containing the comma-separated values to SPLIT and use the fullselect variant
of the IN predicate:

[sql,subs="quotes"]
----
select *
  from sysibm.systables
 where name in (select token from table(split(:TABNAMES)));
----

If the TABNAMES host variable contains the value `EMP,DEPT,PARTS,SUPPLIERS`, this query would be equivalent to

[sql,subs="quotes"]
----
select *
  from sysibm.systables
 where name in ('EMP', 'DEPT', 'PARTS', 'SUPPLIERS')
----
 


=== FORMATTIMESTAMP

The FORMATTIMESTAMP function performs locale-sensitive formatting of a timestamp value using Java's DateTimeFormatter.

[sql,subs="quotes"]
----
FORMATTIMESTAMP(_timestamp_, _pattern_)
FORMATTIMESTAMP(_timestamp_, _pattern_, _locale_)
----

timestamp:: A TIMESTAMP value to be formatted.
pattern:: A format pattern string following Java's DateTimeFormatter syntax. See https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/format/DateTimeFormatter.html[DateTimeFormatter documentation] for pattern syntax.
locale:: (Optional) A locale identifier in BCP 47 format (e.g., 'en-US', 'de-DE', 'ja-JP'). If omitted, uses the default locale.

The function returns a character string containing the formatted timestamp.

If called with a null timestamp, returns the null value.

.Example 1: Basic formatting
[sql]
----
select formattimestamp(current timestamp, 'yyyy-MM-dd HH:mm:ss')
  from sysibm.sysdummyu;
----

.Example 2: Locale-specific formatting
[sql]
----
select formattimestamp(current timestamp, 'EEEE, MMMM d, yyyy', 'en-US') as english,
       formattimestamp(current timestamp, 'EEEE, MMMM d, yyyy', 'de-DE') as german,
       formattimestamp(current timestamp, 'EEEE, MMMM d, yyyy', 'ja-JP') as japanese
  from sysibm.sysdummyu;
----

.Result:
[options="header,autowidth"]
|===
|ENGLISH                    |GERMAN                      |JAPANESE
|Friday, February 8, 2026   |Freitag, Februar 8, 2026    |金曜日, 2月 8, 2026
|===

=== SPRINTF

The SPRINTF function performs general string formatting of one or more
arguments of various mixed types, using Java's formatting capabilities.
See https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Formatter.html#org[the Javadoc for java.util.Formatter] for a detailed documentation of the format string.

[sql,subs="quotes"]
----
SPRINTF(_format-string_, PACK(CCSID 1208, _arg1_, _arg2_, ...))
----

format-string:: A format pattern that adheres to Java's format string syntax.
arg1, arg2, ..., argn:: The values to be formatted, passed using the PACK built-in function.

The function returns a character string.

This function allows formatting of multiple values of different data types in a more concise
way than manual formatting using the capabilities of standard SQL.

=== REGEX_MATCHES
[subs="quotes"]
----
REGEX_MATCHES(_string-expression_, _pattern-expression_)
----

string-expression:: An expression that specifies the string in which the search is to take place. This expression must be character string expression that can be converted to VARCHAR(32704).

pattern-expression:: An expression that specifies the regular expression string that is the pattern for the search. 
This expression must be character string expression that can be converted to VARCHAR(32704).

=== REGEX_REPLACE

The REGEX_REPLACE function replaces all occurrences of a regular expression pattern within a string with a replacement string.

[subs="quotes"]
----
REGEX_REPLACE(_string-expression_, _pattern-expression_, _replacement-expression_)
----

string-expression:: An expression that specifies the string in which replacements are to be made. This expression must be a character string expression that can be converted to VARCHAR(32704).

pattern-expression:: An expression that specifies the regular expression pattern to search for. This expression must be a character string expression that can be converted to VARCHAR(32704). The pattern follows Java regular expression syntax.

replacement-expression:: An expression that specifies the replacement string. This expression must be a character string expression that can be converted to VARCHAR(32704). Can include backreferences to captured groups using $1, $2, etc.

The function returns a character string with all matches of the pattern replaced by the replacement string.

If any argument is null, the result is the null value.

If the pattern is invalid, an SQL error (SQLSTATE 10609) is raised.

.Example 1: Simple replacement
[sql]
----
select regex_replace('Hello World', 'World', 'Db2')
  from sysibm.sysdummyu;
----

.Result:
----
Hello Db2
----

.Example 2: Using backreferences
[sql]
----
-- Swap first and last name
select regex_replace('John Doe', '(\w+)\s+(\w+)', '$2, $1')
  from sysibm.sysdummyu;
----

.Result:
----
Doe, John
----

.Example 3: Remove all digits
[sql]
----
select regex_replace('Order123Number456', '\d+', '')
  from sysibm.sysdummyu;
----

.Result:
----
OrderNumber
----

.Example 4: Format phone numbers
[sql]
----
select regex_replace('5551234567', '(\d{3})(\d{3})(\d{4})', '($1) $2-$3')
  from sysibm.sysdummyu;
----

.Result:
----
(555) 123-4567
----

NOTE: The function uses Java's regular expression engine and caches compiled patterns for performance. The pattern cache holds up to 100 patterns using an LRU (Least Recently Used) eviction policy.

=== TO_ROMAN

This extremely useful UDF converts a small integer
to a https://en.wikipedia.org/wiki/Roman_numerals[roman numeral].
Only values in the range [1..9999] are allowed.

[subs="quotes"]
----
TO_ROMAN(_number_)
----

number:: The number to be converted. It must be a small integer in the range 1 to 9999.

The function returns a character string that is the roman numeral representation of
the given number, in classical subtractive notation. That is, 40 is represented as IX,
900 as CM, etc.

If the number is outside the allowed range, SQLSTATE 77753 is raised.

If called with a null input, the function returns the null value.

.Example:
[source,sql]
----
select to_roman(year(current date))
    as current_year_roman
  from sysibm.sysdummyu;
----

.Result:
....
 CURRENT_YEAR_ROMAN
 ------------------
 MMXXIV
....

== Base64 encoding and decoding

The two functions BASE64ENCODE and BASE64DECODE provide encoding and
decoding between binary values and their Base64 representation. The
binary values can be supplied as either VARBINARY or BLOB data types.

=== BASE64ENCODE

[sql,subs="quotes"]
----
base64encode (_data_ blob(64m))
  returns clob(64m) ccsid unicode
  
base64encode (_data_ varbinary(24528))
  returns varchar(32704) ccsid unicode
----

data:: The data to be Base-64 encoded, as either VARCHAR or BLOB.

Returns the Base-64 representation of the input data.
The length of the returned character data will be about 33% larger than the length of the input data.

If called with a null input, returns the null value.

.Example
....
select base64encode(cast('Uli Seelbach' as blob))
  from sysibm.sysdummyu;
....

=== BASE64DECODE

[sql,subs="quotes"]
----
base64decode (_data_ clob(64m))
  returns blob(64m)
  
base64decode (_data_ varchar(32704))
  returns varbinary(24528)
----

data:: The data to be Base-64 decoded, as either VARCHAR or CLOB.

Returns the decoded input data.
The length of the returned binary data will be about 75% that of the input data.

If called with a null input, returns the null value.


== System utility functions

=== DB2UTILITY

Runs one or more Db2 utility statements.

[sql,subs="quotes"]
----
db2utility(_utilid_ varchar(16), _stmt_ clob ccsid unicode)
  returns integer
----

utilid:: Utility ID or NULL. If NULL, the procedure generates a random utility ID.
stmt::  The utility statement(s).

The function runs the supplied Db2 utility statements and returns the highest
return code from running the utility if it was 4 or less. Otherwise,
an SQL condition with SQLSTATE 5UA99 is issued. 

The utility output is returned in global variable `UTILITY_OUTPUT`, regardless
of the return code.
 

=== RUNSTATS

Performs a RUNSTATS operation against the specified tables.

[sql,subs="quotes"]
----
runstats(objects, schema_pattern, object_name_pattern, statement)
----

objects:: Determines what kind of objects the following parameters specify; 
can be either 'TABLES' or 'DATABASE'. The spelling is case insensitive.
schema_pattern:: When _objects_ is `TABLES`, specifies the schema name pattern of the tables.
When objects is DATABASE, specifies the database name pattern.
object_name_pattern:: When objects is TABLES, specifies the table name pattern of the tables.
When objects is DATABASE, specifies the tablespace name pattern. If null, this means
all tables within the schema, or all tablespaces within the database.
statement:: The RUNSTATS statistics-spec. If null or empty, defaults to `USE PROFILE SORTDEVT SYSALLDA`.

The result of the function is the return code from DSNUTILV.

If the RUNSTATS utility ended in error (RC > 4), an error condition is signaled.

The output of the RUNSTATS utility is returned in global variable UTILITY_OUTPUT and also
in the SYSIBM.SYSPRINT global temporary table. This is true even when the utility
ended in error.

.Example
[source,sql]
----
select runstats('database', 'DSN8D13L', '', '')
     , utility_output 
  from sysibm.sysdummyu;
  
-- or

select runstats('database', 'DSN8D13L', '', '')
  from sysibm.sysdummyu;
select substr(text, 2) from sysibm.sysprint;
----

=== CROSSLOAD

This family of functions copies data from one or more source tables to corresponding target tables 
using the Db2 cross-loader function.

[sql,subs="quotes"]
----
crossload(_sourceselect_, _targetschema_, _targettable_, _tmpspace_)
----

sourceselect:: A SELECT statement that returns the data to be copied from the source table.
targetschema:: The schema name of the target table.
targettable:: The name of the target table.
tmpspace:: Temp space in MB to be allocated for the LOAD utility. Defaults to 5 MB if set to NULL.

The function returns the return code from the LOAD utility if that return code was 4 or less.
If the return code is greater than 4, an error condition is signalled.

[subs="quotes"]
----
crossload(_sourceschema_, _sourcetable_, _targetschema_, _targettable_)
----
sourcescheme:: The schema name of the source table
sourcetable:: The name of the source table.
targetschema:: The schema name of the target table.
targettable:: The name of the target table.

Copies the contents of the source table to the target table. Only columns are copied
that are common to both tables and that are updateable in the target table (this excludes
GENERATED ALWAYS columns).

[subs="quotes"]
----
crossload(_sourceschema_, _targetschema_)     
----

[[:submit]]
=== SUBMIT and SUBMIT_T

SUBMIT and SUBMIT_T submit a job to an internal reader, wait for job
completion, and return the job's spool output. SUBMIT is a scalar function
that returns the job output as a CLOB; SUBMIT_T is a table function and returns
the job output as one row per line of output.

[subs="quotes"]
----
submit(_jcl_)
----

[subs="quotes"]
----
submit_t(_jcl_)
----

jcl:: The JCL text to submit. The data type is CLOB.

.Example
....
with job(jcl) as (
select '
//TEST JOB ,NOTIFY=&SYSUID
//DISPL  EXEC PGM=IEFBR14'
  from sysibm.sysdummyu
)
select submit(jcl) as sysout
  from job
....

The function waits for the submitted job to complete before returning.
It checks for job completion immediately after submission and then each second.

WARNING: It is therefore likely that the function will run for at least one second.
Internally, it uses the Unix sleep command to delay execution, and the minimum
delay that can be specified is one second.
If the job does not end in a timely manner (for example, if it is waiting for reply to a WTOR),
the calling program may be suspended for a long time.

=== APFLIST

The APFLIST table function returns a list of all APF authorized datasets on the system.
It works only on systems with dynamic APF enabled.

[sql,subs="quotes"]
----
function apflist()
  returns table(seqid  integer, 
                dsname varchar(44), 
                volume varchar(6))
----

Example:

[sql,subs="quotes"]
----
select *
  from table(apflist());
----

[options="header,autowidth",width="100%"]
|===
| SEQID | DSNAME          |     VOLUME
|     1 | SYS1.LINKLIB    |     A3RES1
|     2 | SYS1.SVCLIB     |     A3RES1
|     3 | SYS1.SHASLNKE   |     A3RES1
|     4 | SYS1.SIEAMIGE   |     A3RES1
|  ...  | ...             |     ...
|===
  
=== RACFPROFILE

The RACFPROFILE function returns the name of the RACF profile that covers the given data set.

[sql,subs="quotes"]
----
function racfprofile(_dsname_ varchar(44), _volume_ char(6))
  returns varchar(44)
----

dsname:: Name of an existing dataset.
volume:: Volume serial or NULL.

This function returns the RACF profile that covers the named data set
on the given volume; if _volume_ is null, the data set is looked up
in the catalog.

NOTE: Due to a restriction of the underlying RACF callable service,
https://www.ibm.com/docs/en/zos/3.1.0?topic=mfa-r-admin-irrseq00-authentication-factor-service[IRRSEQ00],
the function works with _existing_ data sets only
(unlike the RACF LISTDSD command which also works with non-existing data sets
and returns the name of the profile that would cover the data set
if it existed).

Example:

[sql,subs="quotes"]
----
select racfprofile('ADCDMST.JOB.CNTL', cast(NULL as char(6))) as racf_profile
  from sysibm.sysdummyu;
----

[options="header,autowidth",width="100%"]
|===
| RACF_PROFILE
| ADCDMST.*
|===


=== READ_GENERIC_FILE

This generic table UDF reads records from a flat file and returns them
as relational rows, according to the column specification in the
SELECT statement's typed-correlation-clause.

[subs="quotes"]
----
READ_GENERIC_FILE(_filename_, _flags_)
----

filename:: The name of the file to be read. It must refer to a data set or a PDS(E) member.
flags:: A short integer that contains flags which influence error handling.

The file can be any kind of file that can be read using the C fread()
function, including sequential files (fixed or variable), PDS(E) members
(fixed or variable), and VSAM KSDS or ESDS.

Here is an example of a SELECT statement using the UDF:

.Example
[source,sql]
....
SELECT *
  FROM TABLE(READ_GENERIC_FILE('ADCDMST.FLAT.TEST')) T (
          id     char(8)
        , name   varchar(20)
        , int64  bigint
        , int32  integer
        , int16  smallint
        , dec7_2 decimal(13, 2)
        , ddd    date
        , tm     time
        , rst    varbinary(80)
        )
....

The UDF expects the flat file to be in a format that is in sync with the
column specification in the typed correlation clause, that is, each
supported SQL type corresponds with a native type that may be described,
for example, with a COBOL picture clause.

In this example, the records in file ADCDMST.FLAT.TEST are expected to
be in the following format:

[options="header,autowidth",cols=">,>,<"]
|===
|Offset|Length|Description
|1|8|Alphanumeric bytes
|9|20|Alphanumeric bytes 
|29|8|Binary doubleword 
|37|4|Binary fullword
|41|2|Binary halfword 
|43|8|Date in zoned decimal format (YYYYMMDD)
|51|4|Time time in zoned decimal format (hhmm)
|55|n|Up to 80 alphanumeric bytes
|===

The following SQL types are supported, and correspond to the respective
native data types:

[cols=",",options="header",]
|===
|SQL type |COBOL type
|`VARCHAR(_n_)`       |`PIC X(_n_)`
|`BINARY(_n_)`        |`PIC X(_n_)`
|`VARBINARY(_n_)`     |`PIC X(_n_)`
|`SMALLINT`           |`PIC S9(4)      COMP-5`
|`INTEGER`            |`PIC S9(9)      COMP-5`
|`BIGINT`             |`PIC S9(18)    COMP-5`
|`DECIMAL(_p_, _s_)` |`PIC S9(_p_)V(_s_)  COMP-3`
|`DATE`               |`PIC 9999-99-99 DISPLAY`
|`TIME`               |`PIC 99.99      DISPLAY`
|===



== Troubleshooting

=== Common Issues

==== Java Functions Fail with ClassNotFoundException

*Symptoms*: Function execution fails with SQLCODE -430 or -4302

*Cause*: JAR file not properly installed in Db2 or not in WLM environment CLASSPATH

*Solution*:
1. Verify JAR installation:
+
[sql]
----
SELECT JAR_ID, JAR_NAME, JAR_OWNER
  FROM SYSIBM.SYSJARINFO
 WHERE JAR_NAME LIKE '%ROUTINES%';
----

2. If not installed, install using:
+
[sql]
----
CALL SQLJ.DB2_INSTALL_JAR('file:///path/to/routines.jar', 'SCHEMA.ROUTINES', 0);
----

3. Refresh WLM environment:
+
[sql]
----
CALL SYSPROC.WLM_REFRESH('WLMENV', NULL, ?, ?);
----

==== C/COBOL Functions Fail with ABEND

*Symptoms*: Function execution results in ABEND (e.g., S0C4, S806)

*Cause*: Load module not in WLM environment STEPLIB or incompatible compile options

*Solution*:
1. Verify load module location:
   - Check WLM environment definition in DSNZPARM
   - Ensure STEPLIB includes the load library
   - Verify module name matches EXTERNAL NAME in CREATE FUNCTION

2. Check compile options:
   - C functions must be compiled with XPLINK
   - COBOL functions must match WLM environment settings
   - Verify RUN OPTIONS in function definition

==== Function Returns Incorrect Results

*Symptoms*: Function executes but returns unexpected values

*Cause*: Data type mismatch, encoding issues, or logic errors

*Solution*:
1. Verify parameter data types match function signature
2. Check CCSID settings (especially for VARCHAR parameters)
3. Review function logic with test cases
4. Enable debug mode if available (see function-specific documentation)

==== Performance Issues

*Symptoms*: Function execution is slow or times out

*Cause*: Inefficient implementation, large data volumes, or resource constraints

*Solution*:
1. Check ASUTIME limit in function definition
2. Review function implementation for optimization opportunities
3. For regex functions: simplify patterns or use caching
4. For table functions: consider adding WHERE clauses to limit rows
5. Monitor WLM environment resources

==== Permission Denied Errors

*Symptoms*: SQLCODE -551 (authorization failure)

*Cause*: User lacks EXECUTE privilege on function

*Solution*:
[sql]
----
-- Grant execute privilege
GRANT EXECUTE ON FUNCTION schema.function_name TO user_or_role;

-- Or grant to PUBLIC (use with caution)
GRANT EXECUTE ON FUNCTION schema.function_name TO PUBLIC;
----

=== Getting Help

If you encounter issues not covered here:

1. Check the function-specific documentation above
2. Review the link:SECURITY.md[Security Policy] for security-related issues
3. Search existing GitHub issues
4. Create a new issue with:
   - Function name and version
   - Db2 version and z/OS level
   - Complete error message
   - Steps to reproduce
   - Expected vs actual behavior

== Performance Considerations

=== Function Execution Costs

Different implementation languages have different performance characteristics:

[options="header,autowidth"]
|===
|Implementation |Startup Cost |Execution Speed |Best For
|SQL            |Low          |Fast            |Simple logic, set operations
|Java           |Medium       |Medium          |Complex logic, existing libraries
|C              |Low          |Very Fast       |High-performance, system access
|COBOL          |Low          |Fast            |Mainframe integration, existing code
|===

=== Optimization Tips

1. **Use SQL functions when possible** - Lowest overhead, best optimizer integration
2. **Cache compiled patterns** - Regex functions already do this
3. **Limit table function output** - Use WHERE clauses to filter early
4. **Set appropriate ASUTIME** - Balance between timeout and resource usage
5. **Use DETERMINISTIC** - Allows Db2 to cache results when appropriate
6. **Consider ALLOW PARALLEL** - For functions that can run in parallel

=== Monitoring Function Performance

[sql]
----
-- Check function execution statistics
SELECT SCHEMA, NAME, ROUTINE_TYPE,
       INITIAL_INSTS, INITIAL_IOS,
       AVGCPUTIME, AVGIOTIM
  FROM SYSIBM.SYSROUTINES
 WHERE SCHEMA = 'SYSFUN'
 ORDER BY AVGCPUTIME DESC;
----

== Architecture

=== Component Overview

The project consists of multiple layers:

----
┌─────────────────────────────────────────┐
│         SQL Applications                 │
│    (SPUFI, DSNTEP2, Applications)       │
└─────────────────────────────────────────┘
                    │
                    ▼
┌─────────────────────────────────────────┐
│         Db2 SQL Engine                   │
│  ┌─────────────────────────────────┐   │
│  │   SQL Functions (Native)         │   │
│  └─────────────────────────────────┘   │
│  ┌─────────────────────────────────┐   │
│  │   External Function Interface    │   │
│  └─────────────────────────────────┘   │
└─────────────────────────────────────────┘
         │              │              │
         ▼              ▼              ▼
┌──────────────┐ ┌──────────┐ ┌──────────────┐
│ WLM Java Env │ │ WLM C/C++│ │ WLM COBOL    │
│              │ │ Env      │ │ Env          │
│ ┌──────────┐ │ │┌────────┐│ │┌────────────┐│
│ │Java UDFs │ │ ││C UDFs  ││ ││COBOL UDFs  ││
│ │(JAR)     │ │ ││(Load   ││ ││(Load       ││
│ │          │ │ ││Module) ││ ││Module)     ││
│ └──────────┘ │ │└────────┘│ │└────────────┘│
└──────────────┘ └──────────┘ └──────────────┘
----

=== Deployment Architecture

1. **SQL Functions**: Deployed via CREATE FUNCTION DDL
2. **Java Functions**: 
   - JAR installed via SQLJ.DB2_INSTALL_JAR
   - Or placed in WLM environment CLASSPATH
3. **C/COBOL Functions**:
   - Load modules in WLM environment STEPLIB
   - Must be in authorized libraries if APF-required

== Version History

=== Current Version
- Multiple functions across categories
- Support for Db2 12 and 13
- Comprehensive documentation

=== Future Enhancements
See link:ANALYSIS_AND_RECOMMENDATIONS.md[Analysis and Recommendations] for planned improvements.

== License

[Add appropriate license information]

== Contributors

[Add contributor acknowledgments]

== Acknowledgments

Special thanks to the Db2 for z/OS community for inspiration and feedback.
